version: '3.8'

services:
  postgres-db:
    build:
      context: ./SQL
      dockerfile: Dockerfile
    container_name: postgres-container
    ports:
      - "5432:5432"
    env_file:
      - ./SQL/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  flask-backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: flask-backend
    ports:
      - "5000:5000"
    env_file:
      - ./src/.env
    depends_on:
      - postgres-db
    networks:
      - app-network

  react-frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "5173:5173"
    depends_on:
      - flask-backend
    networks:
      - app-network

volumes:
  postgres-data:


networks:
  app-network:
    driver: bridge
